[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.19'
auto_detect_remappings = false # remappings in remappings.txt
optimizer_runs = 10_000
# via_ir = true
ignored_error_codes = []
bytecode_hash = "none"
fs_permissions = [
    { access = "read", path = "./optimized-out" },
    { access = "read", path = "./reference-out" },
    { access = "read", path = "./lib/seaport/optimized-out" },
    { access = "read", path = "./lib/seaport/reference-out" },
]

[profile.upgradeable]
src = 'src-upgradeable/src/'

[profile.ir_inspect]
test = 'src'

[rpc_endpoints]
goerli = '${GOERLI_RPC_URL}'
mainnet = '${ETHEREUM_RPC_URL}'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config